import { makeStyles } from '@mui/styles';

export default makeStyles((theme) => ({
  bannerContainer: {
    [theme.breakpoints.down('sm')]: {
      height: '100vh',
    },
    [theme.breakpoints.only('sm')]: {
      height: '100vh',
    },
    [theme.breakpoints.up('lg')]: {
      height: '100vh',
    },
  },
  featuredInContainerGlassEffect: {
    [theme.breakpoints.down('lg')]: {
      position: 'absolute',
      height: '268px',
      width: '268px',
      left: '50%',
      transform: 'translateX(-50%)',
      top: '717px',
      borderRadius: '500px',
      background: '#5d1df1',
      filter: 'blur(120px)',
      zIndex: 3,
    },
    [theme.breakpoints.up('lg')]: {
      position: 'absolute',
      height: '268px',
      width: '268px',
      left: '486px',
      top: '717px',
      borderRadius: '500px',
      background: '#5d1df1',
      filter: 'blur(120px)',
      zIndex: 3,
    },
  },
  rightSideHeroContainerGlassEffect: {
    [theme.breakpoints.down('lg')]: {
      position: 'absolute',
      zindex: 3,
      width: '120px',
      height: '268.24px',
      right: 0,
      top: '150px',
      background: '#00c8c8',
      filter: 'blur(50px)',
    },
    [theme.breakpoints.up('lg')]: {
      position: 'absolute',
      zIndex: 3,
      width: '120px',
      height: '268.24px',
      right: 0,
      top: '435px',
      background: '#00c8c8',
      filter: 'blur(75px)',
    },
  },
  leftSideHeroContainerGlassEffect: {
    [theme.breakpoints.down('lg')]: {
      position: 'absolute',
      width: '268.24px',
      height: '268.24px',
      left: '-90.43px',
      top: '130.25px',
      background: '#6ab3df',
      filter: 'blur(75px)',
      zIndex: 3,
    },
    [theme.breakpoints.up('lg')]: {
      position: 'absolute',
      width: '268.24px',
      height: '268.24px',
      left: '-101.43px',
      top: '216.25px',
      background: '#6ab3df',
      filter: 'blur(75px)',
      zIndex: 3,
    },
  },
  rightSideFindAWallContainerGlassEffect: {
    [theme.breakpoints.up('sm')]: {
      position: 'absolute',
      width: '268.24px',
      height: '268.24px',
      right: '0px',
      top: '2625.59px',
      background: '#6ab3df',
      filter: 'blur(180px)',
      zIndex: -100,
    },
    [theme.breakpoints.up('lg')]: {
      position: 'absolute',
      width: '268.24px',
      height: '268.24px',
      right: '0px',
      top: '2625.59px',
      background: '#6ab3df',
      filter: 'blur(180px)',
      zIndex: -100,
    },
  },
  bannerHeading: {
    [theme.breakpoints.only('xs')]: {
      fontSize: '36px',
      fontWeight: 900,
      fontFamily: 'Montserrat',
      fontStyle: 'normal',
      letterSpacing: '-0.05em',
      backgroundImage:
        'linear-gradient(94.83deg, #FFFFFF 26.58%, #A984FF 44.93%, #64E1DC 54.77%, #6FC2FF 64.82%, #FFFFFF 78.91%) !important',
      backgroundSize: '100%',
      marginTop: '80px',
      WebkitBackgroundClip: 'text',
      WebkitTextFillColor: 'transparent',
    },
    [theme.breakpoints.only('sm')]: {
      fontWeight: 900,
      fontFamily: 'Montserrat',
      fontStyle: 'normal',
      letterSpacing: '-0.05em',
      backgroundImage:
        'linear-gradient(94.83deg, #FFFFFF 26.58%, #A984FF 44.93%, #64E1DC 54.77%, #6FC2FF 64.82%, #FFFFFF 78.91%) !important',
      backgroundSize: '100%',
      marginTop: '80px',
      WebkitBackgroundClip: 'text',
      WebkitTextFillColor: 'transparent',
    },
    [theme.breakpoints.only('md')]: {
      fontSize: '60px',
      fontWeight: 900,
      fontFamily: 'Montserrat',
      fontStyle: 'normal',
      lineHeight: '90px',
      letterSpacing: '-0.05em',
      backgroundImage:
        'linear-gradient(94.83deg, #FFFFFF 26.58%, #A984FF 44.93%, #64E1DC 54.77%, #6FC2FF 64.82%, #FFFFFF 78.91%) !important',
      backgroundSize: '100%',
      marginTop: '100px',
      WebkitBackgroundClip: 'text',
      WebkitTextFillColor: 'transparent',
    },
    [theme.breakpoints.only('lg')]: {
      fontSize: '60px',
      fontWeight: 900,
      fontFamily: 'Montserrat',
      fontStyle: 'normal',
      lineHeight: '90px',
      letterSpacing: '-0.05em',
      backgroundImage:
        'linear-gradient(94.83deg, #FFFFFF 26.58%, #A984FF 44.93%, #64E1DC 54.77%, #6FC2FF 64.82%, #FFFFFF 78.91%) !important',
      backgroundSize: '100%',
      marginTop: '108px',
      WebkitBackgroundClip: 'text',
      WebkitTextFillColor: 'transparent',
      maxWidth: '1016px',
    },
    [theme.breakpoints.only('xl')]: {
      fontSize: '60px',
      fontWeight: 900,
      fontFamily: 'Montserrat',
      fontStyle: 'normal',
      lineHeight: '90px',
      letterSpacing: '-0.05em',
      backgroundImage:
        'linear-gradient(94.83deg, #FFFFFF 26.58%, #A984FF 44.93%, #64E1DC 54.77%, #6FC2FF 64.82%, #FFFFFF 78.91%) !important',
      backgroundSize: '100%',
      marginTop: '120px',
      WebkitBackgroundClip: 'text',
      WebkitTextFillColor: 'transparent',
      maxWidth: '1016px',
    },
  },
  subtitle: {
    [theme.breakpoints.down('md')]: {
      fontFamily: 'Montserrat',
      fontStyle: 'normal',
      fontWeight: 600,
      fontSize: '16px',
      textAlign: 'center',
      color: 'rgba(255, 255, 255, 0.7)',
      marginTop: '1rem',
      marginBottom: '1rem',
    },
    [theme.breakpoints.only('md')]: {
      fontFamily: 'Montserrat',
      fontStyle: 'normal',
      fontWeight: 600,
      fontSize: '24px',
      textAlign: 'center',
      color: 'rgba(255, 255, 255, 0.7)',
    },
    [theme.breakpoints.up('lg')]: {
      fontFamily: 'Montserrat',
      fontStyle: 'normal',
      fontWeight: 600,
      fontSize: '24px',
      lineHeight: '75px',
      textAlign: 'center',
      color: 'rgba(255, 255, 255, 0.7)',
    },
  },
  sectionTitle: {
    [theme.breakpoints.down('sm')]: {
      fontFamily: 'Montserrat',
      fontStyle: 'normal',
      fontWeight: 'bold',
      fontSize: '12px',
      lineHeight: '22px',
      display: 'flex',
      alignItems: 'center',
      textAlign: 'center',
      color: '#6AB3DF',
    },
    [theme.breakpoints.up('md')]: {
      fontFamily: 'Montserrat',
      fontStyle: 'normal',
      fontWeight: 'bold',
      fontSize: '18px',
      lineHeight: '22px',
      display: 'flex',
      alignItems: 'center',
      textAlign: 'center',
      color: '#6AB3DF',
    },
  },
  wallspaceUnderline: {
    [theme.breakpoints.down('sm')]: {
      background: `url('/small-underline-from-proc.png') repeat-x 100% 100%`,
      paddingBottom: '2rem',
      whiteSpace: 'nowrap',
    },
    [theme.breakpoints.up('sm')]: {
      background: `url('/underline-from-proc.png') repeat-x 100% 100%`,
      paddingBottom: '4.2rem',
      whiteSpace: 'nowrap',
    },
  },
}));
