export const ARTIST_GET_SEARCH_REQUEST = 'ARTIST_GET_SEARCH_REQUEST';
export const ARTIST_GET_SEARCH_SUCCESS = 'ARTIST_GET_SEARCH_SUCCESS';
export const ARTIST_GET_SEARCH_FAIL = 'ARTIST_GET_SEARCH_FAIL';
export const ARTIST_GET_LOADMORE_OFFSET = 600;
export const ARTIST_GET_LIMIT = 12;
export const ARTIST_GET_SKIP = 10;
