export const MARKETPLACE_GET_LIST_LOADING = 'MARKETPLACE_GET_LIST_LOADING';
export const MARKETPLACE_GET_LIST_SUCCESS = 'MARKETPLACE_GET_LIST_SUCCESS';
export const MARKETPLACE_GET_LIST_IDLE = 'MARKETPLACE_GET_LIST_IDLE';
export const MARKETPLACE_GET_LIST_FAIL = 'MARKETPLACE_GET_LIST_FAIL';

export const MARKETPLACE_GET_LIST_FOR_MAP_LOADING =
  'MARKETPLACE_GET_LIST_FOR_MAP_LOADING';
export const MARKETPLACE_GET_LIST_FOR_MAP_SUCCESS =
  'MARKETPLACE_GET_LIST_FOR_MAP_SUCCESS';
export const MARKETPLACE_GET_LIST_FOR_MAP_IDLE =
  'MARKETPLACE_GET_LIST_FOR_MAP_IDLE';
export const MARKETPLACE_GET_LIST_FOR_MAP_FAIL =
  'MARKETPLACE_GET_LIST_FOR_MAP_FAIL';

export const MARKETPLACE_GET_MARKER_DETAILS_LOADING =
  'MARKETPLACE_GET_MARKER_DETAILS_LOADING';
export const MARKETPLACE_GET_MARKER_DETAILS_SUCCESS =
  'MARKETPLACE_GET_MARKER_DETAILS_SUCCESS';
export const MARKETPLACE_GET_LIST_FOR_MAP_IDLE_2 =
  'MARKETPLACE_GET_LIST_FOR_MAP_IDLE_2';
export const MARKETPLACE_GET_MARKER_DETAILS_FAIL =
  'MARKETPLACE_GET_MARKER_DETAILS_FAIL';

export const MARKETPLACE_ARTIST_UPDATE_FILTER_AVAILABILITY =
  'MARKETPLACE_ARTIST_UPDATE_FILTER_AVAILABILITY';
export const MARKETPLACE_ARTIST_UPDATE_FILTER_VERIFICATION_STATUS =
  'MARKETPLACE_ARTIST_UPDATE_FILTER_VERIFICATION_STATUS';
export const MARKETPLACE_ARTIST_UPDATE_FILTER_RISING_TALENT_STATUS =
  'MARKETPLACE_ARTIST_UPDATE_FILTER_RISING_TALENT_STATUS';

export const MARKETPLACE_WALL_UPDATE_FILTER_CONDITION =
  'MARKETPLACE_WALL_UPDATE_FILTER_CONDITION';
export const MARKETPLACE_WALL_UPDATE_FILTER_CONSTRUCTION =
  'MARKETPLACE_WALL_UPDATE_FILTER_CONSTRUCTION';

export const MARKETPLACE_GET_REGISTERED_STATES_IDLE =
  'MARKETPLACE_GET_REGISTERED_STATES_IDLE';
export const MARKETPLACE_GET_REGISTERED_STATES_LOADING =
  'MARKETPLACE_GET_REGISTERED_STATES_LOADING';
export const MARKETPLACE_GET_REGISTERED_STATES_SUCCESS =
  'MARKETPLACE_GET_REGISTERED_STATES_SUCCESS';
export const MARKETPLACE_GET_REGISTERED_STATES_FAIL =
  'MARKETPLACE_GET_REGISTERED_STATES_FAIL';

export const MARKETPLACE_GET_ARTIST_CARD_DETAILS_IDLE =
  'MARKETPLACE_GET_ARTIST_CARD_DETAILS_IDLE';
export const MARKETPLACE_GET_ARTIST_CARD_DETAILS_LOADING =
  'MARKETPLACE_GET_ARTIST_CARD_DETAILS_LOADING';
export const MARKETPLACE_GET_ARTIST_CARD_DETAILS_SUCCESS =
  'MARKETPLACE_GET_ARTIST_CARD_DETAILS_SUCCESS';
export const MARKETPLACE_GET_ARTIST_CARD_DETAILS_FAIL =
  'MARKETPLACE_GET_ARTIST_CARD_DETAILS_FAIL';
