export const SUBMIT_SUBSCRIPTION_REQUEST = 'SUBMIT_SUBSCRIPTION_REQUEST';
export const SUBMIT_SUBSCRIPTION_SUCCESS = 'SUBMIT_SUBSCRIPTION_SUCCESS';
export const SUBMIT_SUBSCRIPTION_ERROR = 'SUBMIT_SUBSCRIPTION_ERROR';
